"""add preview fields to file_versions

Revision ID: 4c035682da6c
Revises: 35598876d5f6
Create Date: 2026-07-07 22:55:52.094750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c035682da6c'
down_revision: Union[str, Sequence[str], None] = '35598876d5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_versions', sa.Column('preview_key', sa.String(length=64), nullable=True))
    op.add_column('file_versions', sa.Column('preview_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_versions', 'preview_size')
    op.drop_column('file_versions', 'preview_key')
    # ### end Alembic commands ###
