"""add composite indexes for files and audit_log

Revision ID: adf47b470ba6
Revises: 4c035682da6c
Create Date: 2026-07-08 20:01:07.643036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf47b470ba6'
down_revision: Union[str, Sequence[str], None] = '4c035682da6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_log_file_created', 'audit_log', ['file_id', 'created_at'], unique=False)
    op.create_index('uq_files_folder_name_active', 'files', ['folder_id', 'name'], unique=True, sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_files_folder_name_active', table_name='files', sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_audit_log_file_created', table_name='audit_log')
    # ### end Alembic commands ###
